name = "sinon-warring-states-game"
main = ".open-next/worker.js"
compatibility_date = "2026-02-26"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_ENV = "base"
PUBLIC_APP_URL = "https://game.sinon.live"

[env.dev]
name = "sinon-warring-states-game-dev"
routes = ["dev-game.sinon.live/*"]

[env.dev.vars]
APP_ENV = "dev"
PUBLIC_APP_URL = "https://dev-game.sinon.live"

[env.production]
name = "sinon-warring-states-game-prod"
routes = ["game.sinon.live/*"]

[env.production.vars]
APP_ENV = "production"
PUBLIC_APP_URL = "https://game.sinon.live"
